version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest  # Use an appropriate image
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build