version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8-node  # Includes Python 3.8 and Node.js
    working_directory: ~/project

    steps:
      - checkout

      # Install Python dependencies for the Flask backend
      - run:
          name: Install Python dependencies
          command: |
            cd server
            python -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Install Node.js dependencies for the React frontend
      - run:
          name: Install Node.js dependencies
          command: |
            cd client
            npm install

      # Build the React frontend
      - run:
          name: Build React frontend
          command: |
            cd client
            npm run build

      # (Optional) Run backend tests
      - run:
          name: Run Flask backend tests
          command: |
            cd server
            source venv/bin/activate
            if [ -d tests ]; then python -m unittest discover -s tests; fi

      # (Optional) Run frontend tests
      - run:
          name: Run React frontend tests
          command: |
            cd client
            npm test -- --watchAll=false

workflows:
  build_and_test:
    jobs:
      - build
